:CocInstall coc-spell-checker
:CocInstall coc-prettier
:CocInstall coc-git
:CocInstall coc-pyright
:CocInstall coc-json
:CocInstall coc-docker
:CocInstall coc-yaml
:CocInstall coc-snippets
:CocInstall coc-sh
:CocInstall coc-pairs
