return {}
-- vim.api.nvim_set_hl(0, "AvanteDiffText", { bg = "#6F2D3D", blend = 80 })
-- vim.api.nvim_set_hl(0, "AvanteDiffAdd", { bg = "#104935", blend = 80 })
--
-- local function find_project_root()
-- 	local current_dir = vim.fn.getcwd()
-- 	local parent_dir = current_dir
--
-- 	while parent_dir ~= "/" do
-- 		if vim.fn.isdirectory(parent_dir .. "/.git") == 1 then
-- 			return parent_dir
-- 		end
-- 		local new_parent = vim.fn.fnamemodify(parent_dir, ":h")
-- 		if new_parent == parent_dir then -- Reached root or cannot go up
-- 			break
-- 		end
-- 		parent_dir = new_parent
-- 	end
--
-- 	-- If no .git found, return the original cwd
-- 	return current_dir
-- end
--
-- local project_root = find_project_root()
-- print(project_root)
--
-- return {
-- 	"yetone/avante.nvim",
-- 	event = "VeryLazy",
-- 	-- version = false, -- Never set this value to "*"! Never!
-- 	-- version = "master",
-- 	config = function()
-- 		require("mcphub").setup({
-- 			port = 3000, -- Port for the mcp-hub Express server
-- 			-- CRITICAL: Must be an absolute path
-- 			config = vim.fn.expand("/home/sahar/.config/mcphub/servers.json"),
-- 			log = {
-- 				level = vim.log.levels.INFO, -- Adjust verbosity (DEBUG, INFO, WARN, ERROR)
-- 				to_file = true, -- Log to ~/.local/state/nvim/mcphub.log
-- 			},
-- 			on_ready = function()
-- 				vim.notify("MCP Hub backend server is initialized and ready.", vim.log.levels.INFO)
-- 			end,
--
-- 			-- extensions = {
-- 			--   avante = {
-- 			--     make_slash_commands = true, -- make /slash commands from MCP server prompts
-- 			--   },
-- 			-- },
-- 		})
--
-- 		require("avante").setup({
-- 			---@alias Provider "claude" | "openai" | "azure" | "gemini" | "cohere" | "copilot" | string
-- 			provider = "gemini", -- The provider used in Aider mode or in the planning phase of Cursor Planning Mode
-- 			-- WARNING: Since auto-suggestions are a high-frequency operation and therefore expensive,
-- 			-- currently designating it as `copilot` provider is dangerous because: https://github.com/yetone/avante.nvim/issues/1048
-- 			-- Of course, you can reduce the request frequency by increasing `suggestion.debounce`.
-- 			auto_suggestions_provider = "gemini",
-- 			gemini = {
-- 				-- model = "gemini-2.5-pro-exp-03-25",
-- 				model = "gemini-2.5-flash-preview-04-17",
-- 			},
-- 			-- MCP HUB
-- 			--    -- Dynamically generate system prompt including available MCP tools
-- 			system_prompt = function()
-- 				local hub = require("mcphub").get_hub_instance()
-- 				-- if hub and hub:is_ready() then
-- 				return hub:get_active_servers_prompt() -- Generates prompt listing active tools
-- 				-- else
-- 				--   return "Default system prompt."
-- 				-- end
-- 			end,
-- 			-- Define MCP interaction as a custom tool for Avante agents
-- 			custom_tools = {
-- 				require("mcphub.extensions.avante").mcp_tool(),
-- 			},
-- 			-- END MCP HUB
-- 			cursor_applying_provider = nil, -- The provider used in the applying phase of Cursor Planning Mode, defaults to nil, when nil uses Config.provider as the provider for the applying phase
-- 			-- claude = {
-- 			-- 	endpoint = "https://api.anthropic.com",
-- 			-- 	model = "claude-3-5-sonnet-20241022",
-- 			-- 	temperature = 0,
-- 			-- 	max_tokens = 4096,
-- 			-- },
-- 			---Specify the special dual_boost mode
-- 			---1. enabled: Whether to enable dual_boost mode. Default to false.
-- 			---2. first_provider: The first provider to generate response. Default to "openai".
-- 			---3. second_provider: The second provider to generate response. Default to "claude".
-- 			---4. prompt: The prompt to generate response based on the two reference outputs.
-- 			---5. timeout: Timeout in milliseconds. Default to 60000.
-- 			---How it works:
-- 			--- When dual_boost is enabled, avante will generate two responses from the first_provider and second_provider respectively. Then use the response from the first_provider as provider1_output and the response from the second_provider as provider2_output. Finally, avante will generate a response based on the prompt and the two reference outputs, with the default Provider as normal.
-- 			---Note: This is an experimental feature and may not work as expected.
-- 			dual_boost = {
-- 				enabled = false,
-- 				first_provider = "openai",
-- 				second_provider = "claude",
-- 				prompt = "Based on the two reference outputs below, generate a response that incorporates elements from both but reflects your own judgment and unique perspective. Do not provide any explanation, just give the response directly. Reference Output 1: [{{provider1_output}}], Reference Output 2: [{{provider2_output}}]",
-- 				timeout = 60000, -- Timeout in milliseconds
-- 			},
-- 			behaviour = {
-- 				auto_suggestions = true, -- Experimental stage
-- 				auto_set_highlight_group = true,
-- 				auto_set_keymaps = true,
-- 				auto_apply_diff_after_generation = false,
-- 				support_paste_from_clipboard = true,
-- 				minimize_diff = true, -- Whether to remove unchanged lines when applying a code block
-- 				enable_token_counting = true, -- Whether to enable token counting. Default to true.
-- 				enable_cursor_planning_mode = true, -- Whether to enable Cursor Planning Mode. Default to false.
-- 				enable_claude_text_editor_tool_mode = false, -- Whether to enable Claude Text Editor Tool Mode.
-- 			},
-- 			history = {
-- 				max_tokens = 4096,
-- 				carried_entry_count = nil,
-- 				storage_path = project_root .. "/.avante",
-- 				paste = {
-- 					extension = "png",
-- 					filename = "pasted-%Y-%m-%d-%H-%M-%S",
-- 				},
-- 			},
-- 			mappings = {
-- 				--- @class AvanteConflictMappings
-- 				diff = {
-- 					ours = "co",
-- 					theirs = "ct",
-- 					all_theirs = "ca",
-- 					both = "cb",
-- 					cursor = "cc",
-- 					next = "]x",
-- 					prev = "[x",
-- 				},
-- 				suggestion = {
-- 					accept = "<M-l>",
-- 					next = "<M-]>",
-- 					prev = "<M-[>",
-- 					dismiss = "<C-]>",
-- 				},
-- 				jump = {
-- 					next = "]]",
-- 					prev = "[[",
-- 				},
-- 				submit = {
-- 					normal = "<CR>",
-- 					insert = "<C-s>",
-- 				},
-- 				cancel = {
-- 					normal = { "<C-c>", "<Esc>", "q" },
-- 					insert = { "<C-c>" },
-- 				},
-- 				sidebar = {
-- 					apply_all = "A",
-- 					apply_cursor = "a",
-- 					retry_user_request = "r",
-- 					edit_user_request = "e",
-- 					switch_windows = "<Tab>",
-- 					reverse_switch_windows = "<S-Tab>",
-- 					remove_file = "d",
-- 					add_file = "@",
-- 					close = { "<Esc>", "q" },
-- 					close_from_input = nil, -- e.g., { normal = "<Esc>", insert = "<C-d>" }
-- 				},
-- 			},
-- 			hints = { enabled = true },
-- 			windows = {
-- 				---@type "right" | "left" | "top" | "bottom"
-- 				position = "right", -- the position of the sidebar
-- 				wrap = true, -- similar to vim.o.wrap
-- 				width = 30, -- default % based on available width
-- 				sidebar_header = {
-- 					enabled = true, -- true, false to enable/disable the header
-- 					align = "center", -- left, center, right for title
-- 					rounded = true,
-- 				},
-- 				input = {
-- 					prefix = "> ",
-- 					height = 8, -- Height of the input window in vertical layout
-- 				},
-- 				edit = {
-- 					border = "rounded",
-- 					start_insert = true, -- Start insert mode when opening the edit window
-- 				},
-- 				ask = {
-- 					floating = false, -- Open the 'AvanteAsk' prompt in a floating window
-- 					start_insert = true, -- Start insert mode when opening the ask window
-- 					border = "rounded",
-- 					---@type "ours" | "theirs"
-- 					focus_on_apply = "ours", -- which diff to focus after applying
-- 				},
-- 			},
-- 			highlights = {
-- 				---@type AvanteConflictHighlights
-- 				diff = {
-- 					current = "AvanteDiffText",
-- 					incoming = "AvanteDiffAdd",
-- 				},
-- 			},
-- 			--- @class AvanteConflictUserConfig
-- 			diff = {
-- 				autojump = true,
-- 				---@type string | fun(): any
-- 				list_opener = "copen",
-- 				--- Override the 'timeoutlen' setting while hovering over a diff (see :help timeoutlen).
-- 				--- Helps to avoid entering operator-pending mode with diff mappings starting with `c`.
-- 				--- Disable by setting to -1.
-- 				override_timeoutlen = 500,
-- 			},
-- 			suggestion = {
-- 				debounce = 600,
-- 				throttle = 600,
-- 			},
-- 		})
-- 	end,
-- 	-- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
-- 	build = "make",
-- 	-- build = "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false" -- for windows
-- 	dependencies = {
-- 		"nvim-treesitter/nvim-treesitter",
-- 		"stevearc/dressing.nvim",
-- 		"nvim-lua/plenary.nvim",
-- 		"MunifTanjim/nui.nvim",
-- 		"ravitemer/mcphub.nvim",
-- 		--- The below dependencies are optional,
-- 		"nvim-telescope/telescope.nvim", -- for file_selector provider telescope
-- 		"hrsh7th/nvim-cmp", -- autocompletion for avante commands and mentions
-- 		"nvim-tree/nvim-web-devicons", -- or echasnovski/mini.icons
-- 		{
-- 			-- support for image pasting
-- 			"HakonHarnes/img-clip.nvim",
-- 			event = "VeryLazy",
-- 			opts = {
-- 				-- recommended settings
-- 				default = {
-- 					embed_image_as_base64 = false,
-- 					prompt_for_file_name = false,
-- 					drag_and_drop = {
-- 						insert_mode = true,
-- 					},
-- 					-- required for Windows users
-- 					use_absolute_path = true,
-- 				},
-- 			},
-- 		},
-- 		{
-- 			-- Make sure to set this up properly if you have lazy=true
-- 			"MeanderingProgrammer/render-markdown.nvim",
-- 			opts = {
-- 				file_types = { "markdown", "Avante" },
-- 			},
-- 			ft = { "markdown", "Avante" },
-- 		},
-- 	},
-- }
